/*
 * Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models_api

type NeCommandData struct {
	NeId    int64  `json:"ne-id,omitempty"`
	Ip      string `json:"ip,omitempty"`
	Port    int32  `json:"port,omitempty"`
	BaseUrl string `json:"base-url,omitempty"`
}
