/*
 * Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models_api

type TokenRequestResponse struct {

	Status float64 `json:"status,omitempty"`

	AccessToken string `json:"access-token,omitempty"`
}
