/*
 * Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models_api

type ErrorResponse struct {

	Status int32 `json:"status,omitempty"`

	Message string `json:"message,omitempty"`
}
