/*
 * Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models_api

type UserRole struct {
	Id     uint `json:"id"`
	UserId uint `json:"user-id,omitempty"`
	RoleId uint `json:"role-id,omitempty"`
}
