/*
 * Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models_api

type User struct {
	Id          uint   `json:"id,omitempty"`
	Username    string `json:"username,omitempty"`
	Password    string `json:"password,omitempty"`
	Active      bool   `json:"active,omitempty"`
	FullName    string `json:"full-name,omitempty"`
	PhoneNumber string `json:"phone-number,omitempty"`
	FailAttempt int32  `json:"fail-attempt,omitempty"`
	Email       string `json:"email,omitempty"`
	CreatedBy   string `json:"created-by,omitempty"`
	DisableDate uint64 `json:"disable-date,omitempty"`
	CreatedDate uint64 `json:"created-date,omitempty"`
}
