/*
 * Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models_api

type UserAllowedNeList struct {

	Username string `json:"username,omitempty"`

	NeId []int32 `json:"ne-id,omitempty"`
}
