/*
 * Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models_api

type UserPermission struct {

	Username string `json:"username,omitempty"`

	Permission string `json:"permission,omitempty"`
}
