/*
 * Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models_api

type NeCommandResponse struct {

	Code string `json:"code,omitempty"`

	Message string `json:"message,omitempty"`

	NeCommandList []NeCommandData `json:"ne-command-list,omitempty"`
}
