/*
 * Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models_api

type HistoryResponse struct {
	Limit       float64   `json:"limit,omitempty"`
	From        float64   `json:"from,omitempty"`
	To          float64   `json:"to,omitempty"`
	HistoryList []History `json:"history-list,omitempty"`
}
