/*
 * Management service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models_api

type NeData struct {
	NeId             uint   `json:"ne-id,omitempty"`
	Name             string `json:"name,omitempty"`
	Url              string `json:"url"`
	Type             string `json:"type,omitempty"`
	MasterIpConfig   string `json:"master-ip-config,omitempty"`
	MasterPortConfig int32  `json:"master-port-config,omitempty"`
	SlaveIpConfig    string `json:"slave-ip-config,omitempty"`
	SlavePortConfig  int32  `json:"slave-port-config,omitempty"`
	IpCommand        string `json:"ip-command,omitempty"`
	PortCommand      int32  `json:"port-command,omitempty"`
	Description      string `json:"description,omitempty"`
	Namespace        string `json:"namespace,omitempty"`
}
